default: example
	
mealy: mealy_machine_test.c
	gcc mealy_machine_test.c -o mealy_machine_test.exe -std=c18 -Wall -pedantic

moore: moore_machine_test.c
	gcc moore_machine_test.c -o moore_machine_test.exe -std=c18 -Wall -pedantic	
	
clean: 
	rm -f mealy_machine_test.exe
	rm -f moore_machine_test.exe
