default: example02

L04_Example_01: L04_Example_01.c
	gcc L04_Example_01.c -o L04_Example_01.exe -std=c18 -Wall -pedantic	

L04_Example_02: L04_Example_02.c
	gcc L04_Example_02.c -o L04_Example_02.exe -std=c18 -Wall -pedantic	

L04_Example_02_CPP: L04_Example_02.cpp
	g++ L04_Example_02.cpp -o L04_Example_02.exe -std=c++17 -Wall -pedantic	
	
clean: 
	rm -f L04_Example_01.exe
	rm -f L04_Example_02.exe

